// export { default as I18nWidget } from './I18nWidget'
// export { default as Searchbar } from './Searchbar'
export { default as Avatar } from './Avatar'
export { default as FeatureBar } from './FeatureBar'
export { default as Footer } from '../sections/Footer'
export { default as Head } from './Head'
export { default as Navbar } from './Navbar'
export { default as SEO } from './SEO'
export { default as UserNav } from './UserNav'
