export { default as Layout } from './_defaultLayout'
export { default as CourseLayout } from './_courseLayout'

export { default as About } from './About'
export { default as Contact } from './Contact'
export { default as Course } from './Course'
export { default as CourseContent } from './CourseContent'
export { default as Home } from './Home'
export { default as Legalese } from './Legalese'
export { default as Page } from './Page'
export { default as PageNotFound } from './PageNotFound'
export { default as Posts } from './Posts'
export { default as Product } from './Product'
export { default as Products } from './Products'
export { default as UserAccount } from './UserAccount'
